### ISSUE TITLE
WP 5.1.1 available

### ISSUE THREAD

**Issue by soophie** [sevenval/dockerfiles#25]
There is a new WP version out there: 5.1.1 can we update the Wordpress Dockerfile?

We don't need it for every Patch, but for Minor versions we should be up to date.

**Comment by bemeyert** [comment]
@soophie Cheers for bringing this up! We'll take care of it as soon as there's a little bit of time (probably next Friday).

**Comment by jzaefferer** [comment]
Might be enough to bump the version here, and test the result: https://github.com/sevenval/dockerfiles/blob/master/wordpress/Dockerfile#L1

**Comment by soophie** [comment]
I'm not sure if we want to update this file every time a new version is released.

**Comment by bemeyert** [comment]
> I'm not sure if we want to update this file every time a new version is released.
@soophie What else do you propose?
I'll update to 5.1.1-php7.3-apache. S. https://hub.docker.com/_/wordpress

**Comment by bemeyert** [comment]
Is in PR #26 .

**Comment by soophie** [comment]
Why not use `wordpress:5-php7.3-apache`? So we get all Minor and Patches?

**Comment by bemeyert** [comment]
@soophie If that works for you, I'll change the PR.

**Comment by bemeyert** [comment]
I changed the tag to `5-php7.3-apache`. Waiting for review...

**Comment by bemeyert** [comment]
Merged. Images should be available soon.
